config/routes.rb
Rails.application.routes.draw do
  resources :about, only: :index
  resources :flavors
  resources :fillings
  devise_for :users
  resources :users
  get 'photo_uploads/new'
  resources :employees
  resources :clients
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products do
    resources :photo_uploads, only: [:new, :create, :destroy]
  end
   get '/product/promotions' => 'products#promotions'
  resources :categories
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  enum status: [:ativo, :inativo]
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/filling.rb
class Filling < ApplicationRecord
  mount_uploaders :ifillings, IfillingsUploader

  validates :name, uniqueness: true
  
end

app/models/flavor.rb
class Flavor < ApplicationRecord
 mount_uploaders :iflavors, IflavorsUploader
 
 validates :name, uniqueness: true

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  enum status: [:ativo, :inativo]
  mount_uploaders :photos, PhotosUploader
  mount_uploader :image, ImageUploader
  #has_many_attached :photos
  #has_many :fillings
  #has_many :flavors
  
  attr_accessor :remove_photos
  after_save do
    Array(remove_photos).each { |id| photos.find_by_id(id).try(:purge) }
  end
  validates :code, :name, :price, :status, presence: true
  validates :code, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:employee, :admin]
  enum status: [:active, :inactive]
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/fillings_controller.rb
class FillingsController < ApplicationController
  before_action :set_filling, only: [:show, :edit, :update, :destroy]

  # GET /fillings
  # GET /fillings.json
  def index
    @fillings = Filling.all
  end

  # GET /fillings/1
  # GET /fillings/1.json
  def show
  end

  # GET /fillings/new
  def new
    @filling = Filling.new
  end

  # GET /fillings/1/edit
  def edit
  end

  # POST /fillings
  # POST /fillings.json
  def create
    @filling = Filling.new(filling_params)

    respond_to do |format|
      if @filling.save
        format.html { redirect_to @filling, notice: 'Filling was successfully created.' }
        format.json { render :show, status: :created, location: @filling }
      else
        format.html { render :new }
        format.json { render json: @filling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fillings/1
  # PATCH/PUT /fillings/1.json
  def update
    respond_to do |format|
      if @filling.update(filling_params)
        format.html { redirect_to @filling, notice: 'Filling was successfully updated.' }
        format.json { render :show, status: :ok, location: @filling }
      else
        format.html { render :edit }
        format.json { render json: @filling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fillings/1
  # DELETE /fillings/1.json
  def destroy
    @filling.destroy
    respond_to do |format|
      format.html { redirect_to fillings_url, notice: 'Filling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filling
      @filling = Filling.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def filling_params
      params.require(:filling).permit(:name, :description, :price, {ifilling: []})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :role, :status, :obs)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_valor(number)
	  number_to_currency number,
	    unit: "R$ ",
	    separator: ",",
	    delimiter: "."
       end
	def flash_message
    messages = ""
    [:notice, :info, :warning, :error].each {|type|
      if flash[type]
        messages += "<p class=\"#{type}\">#{flash[type]}</p>"
      end
    }

    messages
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def format_status(status)
	if status == 'active'
	 'Ativo'
	else
	 'Inativo'
        end	
   end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/fillings_helper.rb
module FillingsHelper
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photo_uploads_helper.rb
module PhotoUploadsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
   def format_status(status)
	if status == 'active'
	 'Ativo'
	else
	 'Inativo'
        end	
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fillings/_form.html.erb
<%= form_with(model: filling, local: true) do |form| %>
  <% if filling.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(filling.errors.count, "error") %> prohibited this filling from being saved:</h2>

      <ul>
        <% filling.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  
  <div class="form-group">
    <%= f.label :ifillings, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :ifillings, multiple: true, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fillings/edit.html.erb
<h1>Editing Filling</h1>

<%= render 'form', filling: @filling %>

<%= link_to 'Show', @filling %> |
<%= link_to 'Back', fillings_path %>

app/views/fillings/index.html.erb
<p id="notice"><%= notice %></p>

<p class="text-center" style="font-size: large"><b>Recheios dos Pastéis</b></p>
 <div class="row">
      <% @fillings.each do |filling| %>
          <div class="col-md-3 col-sm-3 col-xs-6">
            <p class="text-center" style="font-size: small"><b><%= filling.name %></b></p>
             <% filling.ifillings.each do |photo| %>
              <p><%= link_to image_tag(photo.small_thumb.url, class: "img-responsive img-thumbnail"), filling %></p>
       <% end %>
          </div>
      <% end %>
 </div>
<br>
<%= link_to "home", root_path, :class => 'btn btn-dark btn-sm' %>

app/views/fillings/new.html.erb
<h1>New Filling</h1>

<%= render 'form', filling: @filling %>

<%= link_to 'Back', fillings_path %>

app/views/fillings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @filling.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @filling.description %>
</p>

<p>
  <strong>Preço:</strong>
  <%= @filling.price %>
</p>
<%= link_to 'Voltar', fillings_path %>